### ISSUE TITLE
Update copy for OONI Run site

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-run#2]
Here are some suggestions for copy that could be included on run.ooni.io:

1. Replace "Some inspiring call to action" with "**Let's fight internet censorship together!**"

2. Add a paragraph under the header and before the form including the following copy:

**Choose the sites you want to test, generate a link, and share it with your friends and contacts around the world. Encourage them to run OONI Probe to test the sites of your choice!** 

I also think it's useful to include:

1. Short descriptions (1 sentence) explaining each test. 

2. "Internet Censorship" tags next to Web Connectivity, HTTP Invalid Request Line, and HTTP Header Field Manipulation.

3. "Net Neutrality" tags next to NDT and DASH.

That way, users know what each test does, and what they should expect to uncover by running them.

**Comment by elioqoshi** [comment]
Writing down the descriptions from Slack here:

1. Web Connectivity: "Check if websites are blocked. Learn how this test works here: https://ooni.torproject.org/nettest/web-connectivity/"

2. HTTP Invalid Request Line: "Find middleboxes. Learn how this test works here: https://ooni.torproject.org/nettest/http-invalid-request-line/"

3. HTTP Header Field Manipulation: "Find middleboxes. Learn how this test works here: https://ooni.torproject.org/nettest/http-header-field-manipulation/"

4. NDT: "Measure the speed and performance of your network. Learn how this test works here: https://ooni.torproject.org/nettest/ndt/"

5. DASH: "Measure video streaming performance. Learn how this test works here: https://ooni.torproject.org/nettest/dash/"

**Comment by agrabeli** [comment]
The copy that appears on the side depending on the test that users select should be:

* Web Connectivity*

Generate a link and share it with your friends and contacts around the world. Encourage them to run OONI Probe to test the sites of your choice!

*HTTP Invalid Request Line + HTTP Header Field Manipulation*

Generate a link and share it with your friends and contacts around the world. Encourage them to run OONI Probe to find middleboxes in their networks!

*NDT + DASH*

Generate a link and share it with your friends and contacts around the world. Encourage them to run OONI Probe to measure the speed and performance of their networks!

**Comment by agrabeli** [comment]
Also, for the page that appears when a user clicks on the URL that is "shared with friends" (https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2F%22%5D%7D&mv=1.2.0), please implement the following edits to the copy:

1. Replace the first sentence with "Measure internet censorship by running OONI Probe."

2. 2nd sentence (Under "You have the app"): Add a comma after the word "installed" and delete the word "below".

3. 3rd sentence (Under "Get the app"): Delete the words "on" (before Install) and "below". Write "install" with a capital "I" (for consistency purposes with "Run" in the previous sentence).

**Comment by agrabeli** [comment]
@hellais As a note, it would be great to enable users to share shorter links, if possible.

**Comment by hellais** [comment]
> @hellais As a note, it would be great to enable users to share shorter links, if possible.

I would suggest we use a URL shortening service for that and don't roll out our own url shortener. In any case URL shortening may break universal links on iOS and Android, so it would require some extensive testing.

**Comment by hellais** [comment]
FYI this is how the widgets look like:

<img width="637" alt="screen shot 2017-09-26 at 01 06 26" src="https://user-images.githubusercontent.com/424620/30867643-da465166-a2dc-11e7-9504-f78e98dfb0d6.png">

**Comment by hellais** [comment]
This is done
