### ISSUE TITLE
Add support for multiple URLs

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-run#7]
Currently users are required to add URLs one by one via OONI Run. This can be a painful process if a user wants to add many URLs. I personally have found myself on various occasions wanting to add multiple URLs (more than 30) to OONI Run, and I have received many requests for this by community members.

It would be fantastic if OONI Run could enable users to dump a long list of URLs in a text area, rather than having to manually insert each URL one by one. 

Thanks! :)

**Comment by hellais** [comment]
Possible ways to achieve this are:

* Having a file upload feature to upload a txt with URLs
* Having a modal that shows a text area and the user can copy paste a list of URLs
* Making it possible to hit enter in the text area and populate new rows, possibly also with copy paste support

**Comment by willscott** [comment]
addressed, hopefully, in #8
